In [1]:
import pandas as pd
from sklearn.impute import KNNImputer

In [2]:
base = pd.read_excel("../../Bases/Base_plano_Cartesiano.xlsx")

In [3]:
base

,V0001,V0024,UPA_PNS,V0006_PNS,V0022,A02201|A02305|A02306,C00301,C004,C006,C008,...,P00404,P034|P035,P03701|P03702,P050|P052,P053,P05901|P05902|P05903|P05904,Q074,Q092,Q11006,Q11604
0,11,1110011,110000016,2,4,1,4,5,2,19,...,152.0,0,Não pratica,1,12.0,Fuma atualmente,2,2,2,2
1,11,1110011,110000016,5,2,0,1,1,2,28,...,176.0,1,31-60,4,-1.0,Nunca fumou,2,2,2,2
2,11,1110011,110000016,8,4,1,2,2,2,38,...,156.0,0,Não pratica,2,24.0,Fuma atualmente,2,2,2,2
3,11,1110011,110000016,12,1,2,1,1,1,36,...,172.0,2,61-90,4,-1.0,Nunca fumou,2,2,2,2
4,11,1110011,110000034,4,3,0,1,1,1,42,...,185.0,3,91-120,3,NaN,1-5,2,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43011,53,5310220,530041727,12,4,2,1,1,1,41,...,159.0,0,Não pratica,4,-1.0,Nunca fumou,2,2,2,2
43012,53,5310220,530041727,14,3,0,1,1,1,21,...,178.0,0,Não pratica,1,12.0,Fuma atualmente,2,2,2,2
43013,53,5310220,530044434,6,5,2,2,2,1,44,...,162.0,0,Não pratica,4,-1.0,Nunca fumou,2,2,2,2
43014,53,5310220,530044434,8,6,3,1,1,2,26,...,150.0,0,Não pratica,4,-1.0,Nunca fumou,1,2,2,2
43015,53,5310220,530044434,13,1,2,1,1,1,32,...,186.0,1,61-90,4,-1.0,Nunca fumou,2,2,2,2

In [4]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43016 entries, 0 to 43015
Data columns (total 26 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   V0001                        43016 non-null  int64
 1   V0024                        43016 non-null  int64
 2   UPA_PNS                      43016 non-null  int64
 3   V0006_PNS                    43016 non-null  int64
 4   V0022                        43016 non-null  int64
 5   A02201|A02305|A02306         43016 non-null  int64
 6   C00301                       43016 non-null  int64
 7   C004                         43016 non-null  int64
 8   C006                         43016 non-null  int64
 9   C008                         43016 non-null  int64
 10  C009                         43016 non-null  int64
 11  L01701                       0 non-null      float64
 12  L018                         0 non-null      float64
 13  M01601                       43016 non-null  int64
 14  N010                         43016 non-null  int64
 15  P00104                       42241 non-null  float64
 16  P00404                       42241 non-null  float64
 17  P034|P035                    43016 non-null  int64
 18  P03701|P03702                43016 non-null  object
 19  P050|P052                    43016 non-null  int64
 20  P053                         41386 non-null  float64
 21  P05901|P05902|P05903|P05904  43016 non-null  object
 22  Q074                         43016 non-null  int64
 23  Q092                         43016 non-null  int64
 24  Q11006                       43016 non-null  int64
 25  Q11604                       43016 non-null  int64
dtypes: float64(5), int64(19), object(2)
memory usage: 8.5+ MB

### Separacao das classes

In [5]:
doente = base.loc[base['Q074'] == 1]
n_doente = base.loc[base['Q074'] == 2]

### P00104

#### Doente

In [6]:
doente['P00104'].describe()

count    2149.000000
mean       72.963239
std        16.637415
min        30.000000
25%        61.000000
50%        70.000000
75%        83.000000
max       168.000000
Name: P00104, dtype: float64

In [7]:
doente['P00104'].isna().sum()

61

In [8]:
coluna_alvo = doente[['P00104']]

imputer = KNNImputer(n_neighbors=4)
coluna_imputada = imputer.fit_transform(coluna_alvo)
doente['P00104'] = coluna_imputada

/tmp/ipykernel_17235/3689111258.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  doente['P00104'] = coluna_imputada

In [9]:
doente['P00104'].isna().sum()

0

In [10]:
doente['P00104'].describe()

count    2210.000000
mean       72.963239
std        16.406092
min        30.000000
25%        61.000000
50%        72.000000
75%        82.000000
max       168.000000
Name: P00104, dtype: float64

#### Nao Doente

In [11]:
print(n_doente['P00104'].describe())
print(n_doente['P00104'].isna().sum())

count    40092.000000
mean        72.523870
std         15.580432
min         31.000000
25%         61.000000
50%         70.000000
75%         82.000000
max        176.000000
Name: P00104, dtype: float64
714

In [12]:
coluna_alvo = n_doente[['P00104']]

imputer = KNNImputer(n_neighbors=4)
coluna_imputada = imputer.fit_transform(coluna_alvo)
n_doente['P00104'] = coluna_imputada

/tmp/ipykernel_17235/2204342417.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  n_doente['P00104'] = coluna_imputada

In [13]:
print(n_doente['P00104'].describe())
print(n_doente['P00104'].isna().sum())

count    40806.000000
mean        72.523870
std         15.443518
min         31.000000
25%         62.000000
50%         71.000000
75%         82.000000
max        176.000000
Name: P00104, dtype: float64
0

### P00404

#### Doente

In [14]:
print(doente['P00404'].describe())
print(doente['P00404'].isna().sum())

count    2149.000000
mean      165.631456
std         9.368369
min       141.000000
25%       159.000000
50%       165.000000
75%       172.000000
max       192.000000
Name: P00404, dtype: float64
61

In [15]:
coluna_alvo = doente[['P00404']]
coluna_imputada = imputer.fit_transform(coluna_alvo)
doente['P00404'] = coluna_imputada

/tmp/ipykernel_17235/2556209878.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  doente['P00404'] = coluna_imputada

In [16]:
print(doente['P00404'].describe())
print(doente['P00404'].isna().sum())

count    2210.000000
mean      165.631456
std         9.238113
min       141.000000
25%       159.000000
50%       165.000000
75%       172.000000
max       192.000000
Name: P00404, dtype: float64
0

#### Nao Doente

In [17]:
print(n_doente['P00404'].describe())
print(n_doente['P00404'].isna().sum())

count    40092.000000
mean       165.942283
std          9.398654
min        141.000000
25%        160.000000
50%        165.000000
75%        172.000000
max        192.000000
Name: P00404, dtype: float64
714

In [18]:
coluna_alvo = n_doente[['P00404']]
coluna_imputada = imputer.fit_transform(coluna_alvo)
n_doente['P00404'] = coluna_imputada

/tmp/ipykernel_17235/2665457872.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  n_doente['P00404'] = coluna_imputada

In [19]:
print(n_doente['P00404'].describe())
print(n_doente['P00404'].isna().sum())

count    40806.000000
mean       165.942283
std          9.316063
min        141.000000
25%        160.000000
50%        165.000000
75%        172.000000
max        192.000000
Name: P00404, dtype: float64
0

### P053

### Doente

In [20]:
print(doente['P053'].describe())
print(doente['P053'].isna().sum())

count    2107.000000
mean        3.966303
std         7.769000
min        -1.000000
25%        -1.000000
50%        -1.000000
75%        12.500000
max        24.000000
Name: P053, dtype: float64
103

In [21]:
valores = doente.loc[doente['P053'] != -1]
coluna_alvo = valores[['P053']]
coluna_imputada = imputer.fit_transform(coluna_alvo)
doente.loc[doente['P053'] != -1, 'P053'] = coluna_imputada

In [22]:
print(doente['P053'].describe())
print(doente['P053'].isna().sum())

count    2210.000000
mean        4.504067
std         7.966272
min        -1.000000
25%        -1.000000
50%        -1.000000
75%        14.000000
max        24.000000
Name: P053, dtype: float64
0

In [23]:
doente[['P050|P052', 'P053']]

       P050|P052  P053
8              4  -1.0
45             4  -1.0
78             4  -1.0
85             4  -1.0
91             4  -1.0
...          ...   ...
42912          4  -1.0
42933          4  -1.0
42945          4  -1.0
43004          3  14.0
43014          4  -1.0

[2210 rows x 2 columns]

#### Nao Doente

In [24]:
print(n_doente['P053'].describe())
print(n_doente['P053'].isna().sum())

count    39279.000000
mean         3.407215
std          7.549227
min         -1.000000
25%         -1.000000
50%         -1.000000
75%         10.000000
max         24.000000
Name: P053, dtype: float64
1527

In [25]:
valores = n_doente.loc[n_doente['P053'] != -1]
coluna_alvo = valores[['P053']]
coluna_imputada = imputer.fit_transform(coluna_alvo)
n_doente.loc[n_doente['P053'] != -1, 'P053'] = coluna_imputada

In [26]:
print(n_doente['P053'].describe())
print(n_doente['P053'].isna().sum())

count    40806.000000
mean         3.868487
std          7.767328
min         -1.000000
25%         -1.000000
50%         -1.000000
75%         13.000000
max         24.000000
Name: P053, dtype: float64
0

### Salvando a base

In [27]:
base.loc[base['Q074'] == 1] = doente 
base.loc[base['Q074'] == 2] = n_doente

In [28]:
base.to_excel("../../Bases/Base_sem_vazios.xlsx", index=False)